vich_uploader:
    db_driver: orm
    
    mappings:
        news_image:
            uri_prefix: /images/cover
            upload_destination:  '%kernel.project_dir%/public/images/cover'
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
