index:
    path: /
    controller: App\Controller\BlogController::index
login:
    path: /login
    controller: App\Controller\SecurityController::login
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
signup:
    path: /signup
    controller: App\Controller\RegistrationController::signup
admin:
    path: /admin
    controller: App\Controller\AdminController::homeAdmin
